--- #YAML:1.0
name:               Mojolicious-Plugin-Geo
version:            0.02
abstract:           ~
author:
    - elb0w <elb0w@elbowrage.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mojolicious:  1.78
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
